package com.nikoloz.nikui.securekey;

import android.content.Context;
import android.os.Build;
import android.security.keystore.KeyGenParameterSpec;
import android.security.keystore.KeyInfo;
import android.security.keystore.KeyProperties;
import android.security.keystore.StrongBoxUnavailableException;
import android.security.keystore.UserNotAuthenticatedException;

import androidx.biometric.BiometricManager;
import androidx.biometric.BiometricPrompt;
import androidx.fragment.app.FragmentActivity;

import com.getcapacitor.JSObject;
import com.getcapacitor.Plugin;
import com.getcapacitor.PluginCall;
import com.getcapacitor.PluginMethod;
import com.getcapacitor.annotation.CapacitorPlugin;

import java.security.KeyFactory;
import java.security.KeyPairGenerator;
import java.security.KeyStore;
import java.security.PrivateKey;
import java.security.Signature;
import java.security.spec.ECGenParameterSpec;
import java.util.concurrent.Executor;

import android.util.Base64;

/**
 * This device's key, made inside the Android Keystore — in a StrongBox security
 * chip where the phone has one.
 *
 * The private key is generated by the system and has no software
 * representation: this process can ask for a signature and cannot ask for the
 * key. It is not in a backup, not in the app's data directory, and not readable
 * by a rooted shell.
 *
 * Two conversions are deliberately *not* done here. The public key comes out as
 * SPKI, which the laptop reads, but the signature comes out as DER, which it
 * does not — and that conversion happens in JavaScript, in one place, where a
 * test on a laptop can check it against the laptop's real verifier. Native code
 * that only a device can run is native code that can only be wrong on a device.
 */
@CapacitorPlugin(name = "SecureKey")
public class SecureKeyPlugin extends Plugin {

    private static final String STORE = "AndroidKeyStore";
    private static final String DEFAULT_ALIAS = "nikui.device";

    // MARK: what this device can do

    @PluginMethod
    public void isAvailable(PluginCall call) {
        JSObject out = new JSObject();
        boolean strongBox = getContext().getPackageManager()
            .hasSystemFeature("android.hardware.strongbox_keystore");
        int can = BiometricManager.from(getContext())
            .canAuthenticate(BiometricManager.Authenticators.BIOMETRIC_STRONG
                | BiometricManager.Authenticators.DEVICE_CREDENTIAL);
        out.put("available", true);
        out.put("protection", strongBox ? "strongbox" : "keystore");
        out.put("biometrics", can == BiometricManager.BIOMETRIC_SUCCESS);
        out.put("platform", "android");
        call.resolve(out);
    }

    // MARK: making one

    @PluginMethod
    public void create(PluginCall call) {
        String alias = call.getString("alias", DEFAULT_ALIAS);
        boolean biometric = Boolean.TRUE.equals(call.getBoolean("biometric", false));
        int validity = call.getInt("validitySeconds", 300);

        try {
            remove(alias);
            // StrongBox is a separate chip and not every phone has one; asking
            // for it and accepting the Keystore when it is refused is how you
            // get the best available rather than a crash on a cheaper phone.
            JSObject made = generate(alias, biometric, validity, true);
            if (made == null) made = generate(alias, biometric, validity, false);
            if (made == null) { call.reject("this phone would not make a key"); return; }
            call.resolve(made);
        } catch (Exception error) {
            call.reject("the keystore refused: " + error.getMessage(), error);
        }
    }

    private JSObject generate(String alias, boolean biometric, int validity, boolean strongBox)
            throws Exception {
        KeyGenParameterSpec.Builder spec = new KeyGenParameterSpec.Builder(
                alias, KeyProperties.PURPOSE_SIGN)
            .setAlgorithmParameterSpec(new ECGenParameterSpec("secp256r1"))
            .setDigests(KeyProperties.DIGEST_SHA256);

        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.P) {
            if (strongBox) spec.setIsStrongBoxBacked(true);
            // The key is unusable while the phone is locked. Signing only ever
            // happens with the app on screen, so this costs nothing and takes a
            // stolen unlocked-once phone out of play.
            spec.setUnlockedDeviceRequired(true);
        } else if (strongBox) {
            return null;
        }

        if (biometric) {
            spec.setUserAuthenticationRequired(true);
            if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.R) {
                spec.setUserAuthenticationParameters(validity,
                    KeyProperties.AUTH_BIOMETRIC_STRONG | KeyProperties.AUTH_DEVICE_CREDENTIAL);
            } else {
                spec.setUserAuthenticationValidityDurationSeconds(validity);
            }
            if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.N) {
                // A new fingerprint enrolled on a stolen phone must not inherit
                // the ability to sign. The key dies instead, and the device has
                // to be paired again — which needs the laptop.
                spec.setInvalidatedByBiometricEnrollment(true);
            }
        }

        try {
            KeyPairGenerator generator =
                KeyPairGenerator.getInstance(KeyProperties.KEY_ALGORITHM_EC, STORE);
            generator.initialize(spec.build());
            generator.generateKeyPair();
        } catch (Exception error) {
            if (strongBox && isStrongBoxMissing(error)) return null;
            throw error;
        }

        JSObject out = new JSObject();
        out.put("publicKey", exportPublicKey(alias));
        out.put("protection", where(alias, strongBox));
        out.put("biometric", biometric);
        out.put("alias", alias);
        return out;
    }

    private boolean isStrongBoxMissing(Throwable error) {
        for (Throwable at = error; at != null; at = at.getCause()) {
            if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.P
                    && at instanceof StrongBoxUnavailableException) return true;
            String said = at.getMessage();
            if (said != null && said.toLowerCase().contains("strongbox")) return true;
        }
        return false;
    }

    /** What the system says, rather than what was asked for. */
    private String where(String alias, boolean asked) {
        try {
            KeyStore store = KeyStore.getInstance(STORE);
            store.load(null);
            PrivateKey key = (PrivateKey) store.getKey(alias, null);
            KeyFactory factory = KeyFactory.getInstance(key.getAlgorithm(), STORE);
            KeyInfo info = factory.getKeySpec(key, KeyInfo.class);
            if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.S) {
                int level = info.getSecurityLevel();
                if (level == KeyProperties.SECURITY_LEVEL_STRONGBOX) return "strongbox";
                if (level == KeyProperties.SECURITY_LEVEL_TRUSTED_ENVIRONMENT) return "keystore";
                return "software";
            }
            if (!info.isInsideSecureHardware()) return "software";
        } catch (Exception ignored) {
            // Being unable to ask is not a reason to claim more than is known.
        }
        return asked ? "strongbox" : "keystore";
    }

    /**
     * A key that is absent and a keystore that cannot be asked are different
     * answers. Only the first means the identity is gone and a new one has to be
     * made; the second is a fault that will pass, and reacting to it by making a
     * fresh key would discard a working pairing for nothing.
     */
    @PluginMethod
    public void publicKey(PluginCall call) {
        String alias = call.getString("alias", DEFAULT_ALIAS);
        try {
            KeyStore store = KeyStore.getInstance(STORE);
            store.load(null);
            if (!store.containsAlias(alias)) {
                call.reject("this app holds no key called " + alias, "NO_KEY");
                return;
            }
            JSObject out = new JSObject();
            out.put("publicKey", exportPublicKey(alias));
            out.put("alias", alias);
            call.resolve(out);
        } catch (Exception error) {
            call.reject("the keystore refused: " + error.getMessage(), "KEYSTORE_ERROR", error);
        }
    }

    private String exportPublicKey(String alias) throws Exception {
        KeyStore store = KeyStore.getInstance(STORE);
        store.load(null);
        java.security.cert.Certificate certificate = store.getCertificate(alias);
        if (certificate == null) throw new IllegalStateException("no key under " + alias);
        // Already SPKI — the shape the laptop reads.
        return Base64.encodeToString(certificate.getPublicKey().getEncoded(), Base64.NO_WRAP);
    }

    // MARK: using one

    @PluginMethod
    public void sign(final PluginCall call) {
        final String alias = call.getString("alias", DEFAULT_ALIAS);
        final String message = call.getString("message");
        if (message == null) { call.reject("nothing to sign"); return; }

        try {
            call.resolve(signNow(alias, message));
        } catch (UserNotAuthenticatedException needsYou) {
            // The key is behind a face or a fingerprint and the window has
            // closed. Ask, then sign — rather than failing with something the
            // person cannot act on.
            askThenSign(call, alias, message);
        } catch (Exception error) {
            call.reject("the keystore would not sign: " + error.getMessage(), error);
        }
    }

    private JSObject signNow(String alias, String message) throws Exception {
        KeyStore store = KeyStore.getInstance(STORE);
        store.load(null);
        PrivateKey key = (PrivateKey) store.getKey(alias, null);
        if (key == null) throw new IllegalStateException("no key under " + alias);
        Signature signer = Signature.getInstance("SHA256withECDSA");
        signer.initSign(key);
        signer.update(message.getBytes("UTF-8"));
        JSObject out = new JSObject();
        // DER, as the keystore produces it. Converted in JavaScript.
        out.put("signature", Base64.encodeToString(signer.sign(), Base64.NO_WRAP));
        return out;
    }

    private void askThenSign(final PluginCall call, final String alias, final String message) {
        final FragmentActivity activity = getActivity();
        if (activity == null) { call.reject("nothing on screen to ask with"); return; }
        final String reason = call.getString("reason", "Prove this phone to your laptop");

        activity.runOnUiThread(new Runnable() {
            @Override public void run() {
                Executor onMain = androidx.core.content.ContextCompat.getMainExecutor(activity);
                BiometricPrompt prompt = new BiometricPrompt(activity, onMain,
                    new BiometricPrompt.AuthenticationCallback() {
                        @Override
                        public void onAuthenticationSucceeded(BiometricPrompt.AuthenticationResult result) {
                            try {
                                call.resolve(signNow(alias, message));
                            } catch (Exception error) {
                                call.reject("the keystore would not sign: " + error.getMessage(), error);
                            }
                        }

                        @Override
                        public void onAuthenticationError(int code, CharSequence said) {
                            if (code == BiometricPrompt.ERROR_USER_CANCELED
                                    || code == BiometricPrompt.ERROR_NEGATIVE_BUTTON
                                    || code == BiometricPrompt.ERROR_CANCELED) {
                                call.reject("cancelled", "CANCELLED");
                            } else {
                                call.reject(said == null ? "not unlocked" : said.toString());
                            }
                        }
                    });

                BiometricPrompt.PromptInfo.Builder info = new BiometricPrompt.PromptInfo.Builder()
                    .setTitle("Unlock NikUI")
                    .setSubtitle(reason);
                if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.R) {
                    info.setAllowedAuthenticators(BiometricManager.Authenticators.BIOMETRIC_STRONG
                        | BiometricManager.Authenticators.DEVICE_CREDENTIAL);
                } else {
                    info.setDeviceCredentialAllowed(true);
                }
                prompt.authenticate(info.build());
            }
        });
    }

    // MARK: housekeeping

    @PluginMethod
    public void remove(PluginCall call) {
        remove(call.getString("alias", DEFAULT_ALIAS));
        JSObject out = new JSObject();
        out.put("removed", true);
        call.resolve(out);
    }

    private void remove(String alias) {
        try {
            KeyStore store = KeyStore.getInstance(STORE);
            store.load(null);
            if (store.containsAlias(alias)) store.deleteEntry(alias);
        } catch (Exception ignored) {
            // A key that cannot be found is a key that is gone.
        }
    }
}
