#!/usr/bin/env node
'use strict';

/**
 * The app's web assets, built from the extension's own.
 *
 *   npm run build
 *
 * Nothing in `www/` is written by hand. Every client file is copied from
 * `media/`, and the conversation screen is generated by the very same
 * `renderPage()` the editor's panel uses — so the app cannot quietly become a
 * second client with its own bugs. That has been the rule since the panel and
 * the browser were made to share one set of files, and an app is just a third
 * place to run them.
 *
 * What is app-only lives in `shell/`: the screens a browser never needed —
 * connecting to a laptop in the first place, and settings.
 */

const fs = require('fs');
const path = require('path');

const APP = path.join(__dirname, '..');
const REPO = path.join(APP, '..');
const MEDIA = path.join(REPO, 'media');
const SHELL = path.join(APP, 'shell');
const OUT = path.join(APP, 'www');

const { renderPage, SCRIPTS } = require(path.join(REPO, 'src', 'page.js'));

// Everything the client needs, plus the app's own layer. The list is derived
// rather than typed: whatever the panel loads, the app loads.
const CLIENT_FILES = SCRIPTS.concat([
  'panel.css', 'browser.css', 'mobile.js', 'home.js', 'device.js'
]);

const SHELL_FILES = ['app.css', 'app.js', 'notify.js', 'connect.js', 'settings.js', 'history.js'];

/** The version the app reports to a laptop, so a stale pair can say so. */
function clientVersion() {
  const extension = JSON.parse(fs.readFileSync(path.join(REPO, 'package.json'), 'utf8'));
  const app = JSON.parse(fs.readFileSync(path.join(APP, 'package.json'), 'utf8'));
  return { client: extension.version, app: app.version };
}

function clean(dir) {
  fs.rmSync(dir, { recursive: true, force: true });
  fs.mkdirSync(dir, { recursive: true });
}

function copyClient() {
  const into = path.join(OUT, 'media');
  fs.mkdirSync(into, { recursive: true });
  const copied = [];
  for (const name of new Set(CLIENT_FILES)) {
    const from = path.join(MEDIA, name);
    if (!fs.existsSync(from)) throw new Error('the client is missing ' + name);
    fs.copyFileSync(from, path.join(into, name));
    copied.push(name);
  }
  // Icons too: the app draws its own chrome with the same marks.
  const icons = path.join(MEDIA, 'icons');
  if (fs.existsSync(icons)) {
    fs.mkdirSync(path.join(into, 'icons'), { recursive: true });
    for (const name of fs.readdirSync(icons)) {
      fs.copyFileSync(path.join(icons, name), path.join(into, 'icons', name));
    }
  }
  for (const name of SHELL_FILES) {
    fs.copyFileSync(path.join(SHELL, name), path.join(OUT, name));
  }
  return copied;
}

/**
 * The policy for a page inside the app.
 *
 * Stricter than the served one in the way that matters: the app talks to
 * exactly one laptop over exactly one socket, and loads every byte of itself
 * from its own bundle. `connect-src` has to allow wss to the tailnet, which is
 * not knowable at build time, so it is the one thing left open — and it is only
 * ever used by the transport, which will not talk to a laptop this device has
 * not paired with.
 */
const CSP = [
  "default-src 'none'",
  "img-src 'self' data:",
  "style-src 'self'",
  "script-src 'self'",
  "font-src 'self'",
  // https and wss for a laptop behind a tunnel, and loopback for one on this
  // very machine — which is how somebody tries the app out before a tailnet
  // exists. Nothing else: the app talks to one laptop and to nothing at all
  // otherwise, and there is no remote script that could want more.
  "connect-src 'self' https: wss: http://127.0.0.1:* http://localhost:* ws://127.0.0.1:* ws://localhost:*",
  "base-uri 'none'",
  "form-action 'none'",
  "frame-ancestors 'none'"
].join('; ');

const head = (title, extra) =>
  '<meta name="viewport" content="width=device-width, initial-scale=1.0, viewport-fit=cover, user-scalable=no">\n' +
  `<meta http-equiv="Content-Security-Policy" content="${CSP}">\n` +
  '<meta name="color-scheme" content="dark">\n' +
  `<title>${title}</title>\n` +
  '<link rel="stylesheet" href="media/browser.css">\n' +
  '<link rel="stylesheet" href="app.css">\n' +
  (extra || '');

/**
 * Capacitor's own runtime, copied in rather than bundled.
 *
 * The app has no bundler, and did not appear to need one: Android's bridge
 * builds `Capacitor.Plugins` itself, so every plugin was simply there. iOS does
 * not — `Capacitor.registerPlugin` comes from this file, and without it an
 * iPhone finds none of this app's own plugins and quietly falls back to a
 * browser key. Eight kilobytes, shipped from node_modules like everything else
 * in www/, and checked against its source so it cannot drift.
 */
function copyCapacitor() {
  const from = path.join(APP, 'node_modules', '@capacitor', 'core', 'dist', 'capacitor.js');
  if (!fs.existsSync(from)) {
    throw new Error('@capacitor/core is not installed: run npm install in app/');
  }
  fs.copyFileSync(from, path.join(OUT, 'capacitor.js'));
  return 1;
}

/** A screen that is the app's own, rather than the client's. */
function page({ file, title, body, scripts, cls }) {
  const tags = ['capacitor.js'].concat(scripts || [])
    .map((s) => `  <script src="${s}"></script>`).join('\n');
  fs.writeFileSync(path.join(OUT, file), `<!DOCTYPE html>
<html lang="en" class="app">
<head>
<meta charset="UTF-8">
${head(title)}</head>
<body class="app${cls ? ' ' + cls : ''}">
${body}
${tags}
</body>
</html>
`);
}

/**
 * The conversation, from the same template the panel uses.
 *
 * `renderPage` wants a nonce; inside the bundle every script is local and the
 * policy says `script-src 'self'`, so there is nothing for a nonce to protect
 * against and none is minted. The markup is otherwise identical to the editor's,
 * which is the entire point.
 */
function conversationPage() {
  const html = renderPage({
    asset: (file) => 'media/' + file,
    nonce: 'app',
    csp: CSP,
    // app.js is not deferred: the client reads window.NIKUI_REMOTE the moment
    // it starts, and a deferred script would run after it.
    head: '<link rel="stylesheet" href="media/browser.css">\n' +
      '<link rel="stylesheet" href="app.css">\n' +
      '<script src="capacitor.js"></script>\n' +
      '<script src="app.js"></script>\n' +
      '<script src="notify.js"></script>\n' +
      '<script src="media/mobile.js" defer></script>\n',
    boot: 'document.body.classList.add(\'app\', \'app-conversation\');'
  })
    // The app has no nonces to hand out and no use for them: nothing here is
    // fetched over a network, and the policy already says 'self'.
    .replace(/ nonce="app"/g, '')
    .replace(/<meta name="viewport"[^>]*>/, '<meta name="viewport" content="width=device-width, initial-scale=1.0, viewport-fit=cover, user-scalable=no">');
  fs.writeFileSync(path.join(OUT, 'conversation.html'), html);
}

function homePage() {
  page({
    file: 'index.html',
    title: 'NikUI',
    cls: 'home',
    body: `  <header class="bar">
    <span class="bar-title">Instances</span>
    <div class="bar-right">
      <div class="link" id="link" role="status" aria-live="polite" hidden></div>
    </div>
  </header>
  <main class="screen">
    <p class="lede" id="lede">Connecting&hellip;</p>
    <div class="rows" id="rows"></div>
  </main>
  <nav class="tabs" id="tabs" aria-label="Sections"></nav>`,
    scripts: ['app.js', 'notify.js', 'media/icons.js', 'media/device.js', 'media/secure.js',
      'media/transport.js', 'media/home.js']
  });
}

function connectPage() {
  page({
    file: 'connect.html',
    title: 'Connect',
    cls: 'connect',
    body: `  <main class="screen welcome" id="screen">
    <div class="mark" id="mark"></div>
    <h1 id="headline">Connect to your laptop</h1>
    <p class="lede" id="lede">Two steps, and the second one is pointing this phone at a screen.</p>

    <!-- What somebody sees first: what to do, in order, with nothing to fill in.
         Scanning the code opens this app with everything already in it, so the
         fields below are the fallback rather than the way. -->
    <ol class="steps" id="steps">
      <li><span>1</span><p>On your laptop, run <strong>NikUI: Pair a device</strong>.</p></li>
      <li><span>2</span><p>Point this phone's camera at the square it shows.</p></li>
    </ol>

    <!-- Arrived by scanning: everything is known, so there is one thing to do. -->
    <div class="pane invited" id="invited" hidden>
      <p class="invited-from" id="invited-from">your laptop</p>
      <p class="invited-where" id="invited-where"></p>
      <button class="primary" id="accept" type="button">Pair</button>
      <button class="quiet" id="decline" type="button">Not now</button>
    </div>

    <form class="pane" id="form" autocomplete="off" hidden>
      <label class="field">
        <span class="field-label">Address</span>
        <input id="host" type="text" inputmode="url" autocapitalize="none" autocorrect="off"
               spellcheck="false" placeholder="laptop.tailnet.ts.net">
      </label>
      <label class="field">
        <span class="field-label">Code</span>
        <input id="code" type="text" inputmode="latin" autocapitalize="characters" autocorrect="off"
               spellcheck="false" maxlength="9" placeholder="ABCD2345">
      </label>
      <label class="field">
        <span class="field-label">Name this device</span>
        <input id="name" type="text" maxlength="32" placeholder="My phone">
      </label>
      <button class="primary" id="go" type="submit">Pair</button>
      <button class="quiet" id="paste" type="button">Paste a pairing link instead</button>
    </form>

    <button class="quiet" id="type-instead" type="button">Type the code instead</button>
    <p class="note" id="note" role="status" aria-live="polite"></p>
    <ul class="terms">
      <li id="held">This device makes a key that never leaves it.</li>
      <li>Pairing lets it <strong>watch</strong>. Sending prompts is a separate permission you grant on the laptop.</li>
    </ul>
  </main>`,
    scripts: ['app.js', 'media/device.js', 'connect.js']
  });
}

function historyPage() {
  page({
    file: 'history.html',
    title: 'History',
    cls: 'history',
    body: `  <header class="bar">
    <div class="bar-left"></div>
    <span class="bar-title">History</span>
    <div class="bar-right"></div>
  </header>
  <div class="search-wrap">
    <input id="search" type="search" placeholder="Search past conversations"
           autocapitalize="none" autocorrect="off" spellcheck="false">
  </div>
  <main class="screen" id="screen"></main>
  <nav class="tabs" id="tabs" aria-label="Sections"></nav>`,
    scripts: ['app.js', 'notify.js', 'media/icons.js', 'media/device.js', 'media/secure.js',
      'media/transport.js', 'history.js']
  });
}

function settingsPage() {
  page({
    file: 'settings.html',
    title: 'Settings',
    cls: 'settings',
    body: `  <header class="bar">
    <div class="bar-left"></div>
    <span class="bar-title">Settings</span>
    <div class="bar-right"></div>
  </header>
  <main class="screen" id="screen"></main>
  <nav class="tabs" id="tabs" aria-label="Sections"></nav>`,
    scripts: ['app.js', 'notify.js', 'media/icons.js', 'media/device.js', 'media/secure.js',
      'media/transport.js', 'settings.js']
  });
}

function manifest(version) {
  fs.writeFileSync(path.join(OUT, 'version.json'), JSON.stringify(version, null, 2) + '\n');
}

function build() {
  clean(OUT);
  const version = clientVersion();
  const copied = copyClient();
  copyCapacitor();
  conversationPage();
  homePage();
  historyPage();
  connectPage();
  settingsPage();
  manifest(version);

  const files = fs.readdirSync(OUT).length;
  console.log(`www/ built — ${copied.length} client files, ${files} entries, ` +
    `client ${version.client}, app ${version.app}`);
  return { copied, version };
}

if (require.main === module) {
  try {
    build();
  } catch (err) {
    console.error('build failed: ' + err.message);
    process.exit(1);
  }
}

module.exports = { build, CLIENT_FILES, SHELL_FILES, CSP, OUT };
